apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: resumesmartbuild
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/PROJECT_ID/resumesmartbuild
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: FLASK_ENV
          value: "production"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi